### PR TITLE
[JENKINS-29088] Fix 404 on trends configuration link

### PR DESCRIPTION
**Pull request by amuniz**
https://issues.jenkins-ci.org/browse/JENKINS-29088

It fixes the 404 error when clicking on "You can define the default values for the trend graph in a separate view" (advanced configuration)

### CODE REVIEW

**Comment by amuniz** [comment]
@reviewbybees

**Comment by oleg-nenashev** [comment]
:bug: 
You fix one use-case, but there is a risk of breaking all other ones, which rely on the current ID. The broken link on the Trend Graph should be fixed instead

**Comment by amuniz** [comment]
@oleg-nenashev I manually tested all other use-cases. Everything seems to work fine (saving and recover properties after saving configuration).
 
Moreover, the correct plugin ID is "CppTest" (C in uppercase) as stated here: https://github.com/amuniz/cpptest-plugin/blob/75ab10c9d1e37816da38e45e68389c52744be987/src/main/java/hudson/plugins/cpptest/CpptestPublisher.java#L45

Could you point me to some concrete use-case that you think would be broken?

**Comment by oleg-nenashev** [comment]
A user can add a link from any other plugin including private ones. Such ID changes in Jelly files should be considered as a compatibility breaking changes.

**Comment by amuniz** [comment]
I can not find any use of this URL path in GH organization: https://github.com/search?utf8=%E2%9C%93&q=%22cpptest%2FconfigureDefaults%22+user%3Ajenkinsci

Moreover, this link seems to be broken from ages... I don't think anyone is relying on it.

**Comment by oleg-nenashev** [comment]
Even if nobody uses the id, it's better to follow the compatibility requirements if there's no particular reason to break the compatibility

**Comment by amuniz** [comment]
@oleg-nenashev the URL I'm trying to fix is not a regular plugin resources URL, it's managed (and autogenerated) by analysis-core plugin based on the plugin ID. So there are only two ways to solve this:

 1. Modify the jelly file to use the correct plugin ID (the one I chose)
 2. Modify the plugin ID itself used in Java classes ([here](https://github.com/amuniz/cpptest-plugin/blob/75ab10c9d1e37816da38e45e68389c52744be987/src/main/java/hudson/plugins/cpptest/CpptestPublisher.java#L45) and [here](https://github.com/amuniz/cpptest-plugin/blob/75ab10c9d1e37816da38e45e68389c52744be987/src/main/java/hudson/plugins/cpptest/CpptestDescriptor.java#L19))

I see much more potential issues if we go for the second way.
If you know any other way to fix it, please tell me.

What do you think?

**Comment by oleg-nenashev** [comment]
@amuniz 
If it is bundled to the plugin ID, I'm totally OK if you correct the ID.
:bee:

**Comment by amuniz** [comment]
Increasing core dependency to 1.480 LTS was needed to be able to add some functional tests. In 1.410 an exception is reaised during tests: ```Cannot read property nextSibling from null```. The next LTS solving it is 1.480.

**Comment by oleg-nenashev** [comment]
I think the upgrade to 1.480 is totally OK, but it makes sense to confirm it with @gboissinot 
:bee: from my side

**Comment by stephenc** [comment]
:bee:

**Comment by amuniz** [comment]
@reviewbybees done

**Pull request merged**
